### ISSUE TITLE
'Cobalt 2' Theme missing in latest update

### ISSUE THREAD

**Issue by geodude1992** [vishnuvardhan-s/leetcode-custom-themes#6]
I can see it on the extension when I am not on Leetcode but disappears when I go to leetcode. Please add back its my favorite theme!

**Comment by vishnuvardhan-sairam** [comment]
Hi @geodude1992 ,

I am able to see Cobalt2 in the list and able to apply it to my editor as well

Can you please give me more information here? A video or something.

<img width="868" alt="image" src="https://github.com/vishnuvardhan-s/leetcode-custom-themes/assets/162124585/a6853626-4916-4ea7-8c27-5585da649f4e">

**Comment by vishnuvardhan-s** [comment]
Hi @geodude1992 ,

I am able to see Cobalt2 in the list and able to apply it to my editor as well

Can you please give me more information here? A video or something.

<img width="868" alt="image" src="https://github.com/vishnuvardhan-s/leetcode-custom-themes/assets/45058522/cd46a571-68c8-4592-8a57-754653069b88">

**Comment by geodude1992** [comment]
Here is what I see. It looks like there are more themes missing. Not sure why.
![Screenshot 2024-03-19 163157](https://github.com/vishnuvardhan-s/leetcode-custom-themes/assets/72895219/4e02467d-2783-4f64-bce0-8804a2312fd8)

**Comment by vishnuvardhan-s** [comment]
Are you using the old UI by any chance?

Because, leetcode uses codemirror in their old UI and the new UI uses monaco based editor
The extension auto detects this and lists the themes accordingly.

I can check if Cobalt2 is available for codemirror editor. Meanwhile, can you check this
1. Check if you are using the old leetcode UI
2. If yes, can you switch to new UI and see if Cobalt2 is available in the list?

Thanks!

**Comment by geodude1992** [comment]
Okay yeah for some reason it switch to the old leetcode version not sure how and I though it was the new but I can now see Cobalt 2 thanks

**Comment by geodude1992** [comment]
thanks
